[tool.pyright]

# add any files with type declaration to include
include = ["pettingzoo/atari/base_atari_env.py"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
]
strict = ["gym/version.py", "gym/logger.py"]

reportMissingImports = true
reportMissingTypeStubs = false
verboseOutput = true
