[tool.pyright]

# add any files/directories with type declaration to include
include = [
    "pettingzoo/utils/env.py"
]
exclude = [
]
strict = [
]
# reportMissingImports = true
verboseOutput = true
# typeCheckingMode = "basic"
# pythonVersion = "3.7"

[tool.pytest.ini_options]
norecursedirs = [
    "pettingzoo"
]
