[tool.pyright]

# add any files/directories with type declaration to include
include = ["pettingzoo/atari/base_atari_env.py"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
]
strict = ["pettingzoo/atari/base_atari_env.py"]

reportMissingImports = true
reportMissingTypeStubs = false
verboseOutput = true
