[tool.pyright]

# add any files/directories with type declaration to include
include = [
    "pettingzoo/utils/env.py"
]
exclude = [
]
strict = [
]
verboseOutput = true
typeCheckingMode = "basic"

[tool.pytest.ini_options]
norecursedirs = [
    "pettingzoo"
]
