# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS tests

on:
  push:
    branches: [ master ]

jobs:
  macos-test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install AutoROM pytest -r requirements.txt
        AutoROM -v
    - name: Full Python tests
      run: |
        pytest ./test/pytest_runner.py
        pytest ./test/all_parameter_combs.py
    - name: 13 lines test
      run: |
        pip install stable_baselines3
        sed s/total_timesteps=2000000/total_timesteps=2000/g tutorials/13_lines.py | sed s/n_steps=256/n_steps=16/g | xvfb-run -s "-screen 0 1024x768x24" python -
